config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  mount ResqueWeb::Engine => "/resque_web"

  root "events#index"

  resources :events do
    resources :comments, only: %i[ create destroy ]
    resources :subscriptions, only: %i[ create destroy ]
    resources :photos, only: %i[ create destroy ]

    post :show, on: :member
  end

  resources :users, only: %i[ show edit update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: %i[ create destroy ]
  before_action :set_comment, only: %i[ destroy ]

  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if @new_comment.save
      EventNotificationJob.perform_later(@new_comment)
      redirect_to @event, notice: t("controllers.comments.created")
    else
      render "events/show", status: :unprocessable_entity
    end

  end

  def destroy
    message = { notice: t("controllers.comments.destroyed") }

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = { status: :unprocessable_entity }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="buffer-bottom card">
  <div class="card-body"><%= comment.body %></div>
  <div class="card-footer text-muted d-flex">
    <span>
      <% if comment.user.present? %>
        <%= render partial: "users/user", object: comment.user %>
      <% else %>
        <em><strong><%= comment.user_name %></strong></em>
      <% end %>
    </span>
    <em class="mx-4"><%= l comment.created_at, format: :long %></em>
    <% if current_user_can_edit?(comment) %>
      <%= link_to '<i class="bi bi-trash3"></i>'.html_safe, event_comment_path(comment.event, comment),
            data: { turbo_method: :delete, turbo_confirm: t("turbo.confirm") }, class: "ms-auto"%>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@event, comment] do |form| %>
  <%= render partial: "partials/form_errors", locals: { model: comment } %>

  <div class="col-sm-8 mt-3">
    <%= form.label :body, class: "col-sm-6 col-form-label" %>
    <div class="input-group">
      <div class="input-group-text"><i class="bi bi-clipboard"></i></div>
      <%= form.text_area :body, class: "form-control" %>
    </div>
  </div>

  <% unless user_signed_in? %>
    <div class="col-sm-8 mt-1">
      <%= form.label :user_name, class: "col-sm-6 col-form-label" %>
      <div class="input-group">
        <div class="input-group-text"><i class="bi bi-person-fill"></i></div>
        <%= form.text_field :user_name, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <div class="mt-4">
    <%= form.submit t("button.send"), class: "btn btn-primary" %>
  </div>
<% end %>