config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  mount ResqueWeb::Engine => "/resque_web"

  root "events#index"

  resources :events do
    resources :comments, only: %i[ create destroy ]
    resources :subscriptions, only: %i[ create destroy ]
    resources :photos, only: %i[ create destroy ]

    post :show, on: :member
  end

  resources :users, only: %i[ show edit update]
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :user, presence: true

  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user])
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[ show index ]
  before_action :set_event, only: %i[ show edit update destroy ]

  after_action :verify_authorized, except: %i[ index ]

  def index
    @events = policy_scope(Event)
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])

    authorize @event
  rescue Pundit::NotAuthorizedError
    flash.now[:alert] = t("controllers.events.wrong_pincode") if params[:pincode].present?
    render "password_form"
  end

  def new
    @event = current_user.events.build
    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)
    authorize @event

    if @event.save
      redirect_to event_url(@event), notice: t("controllers.events.created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to event_url(@event), notice: t("controllers.events.updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @event

    @event.destroy

    redirect_to events_url, notice: t("controllers.events.destroyed")
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4 mt-1">
  <div class="thumbnail">

    <%= content_tag "div", '',
                    class: "event-background",
                    style: "background-image: url(#{event_thumb(event)})"
    %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3>
            <small><%= l event.datetime, format: :long %></small>
          </h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: "img-icon", title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: @event) do |form| %>
  <%= render partial: "partials/form_errors", locals: { model: @event } %>

  <div class="col-sm-6 mt-3">
    <%= form.label :title, class: "col-sm-12 col-form-label" %>
    <div class="input-group">
      <div class="input-group-text"><i class="bi bi-pen"></i></div>
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="col-sm-6 mt-1">
    <%= form.label :address, class: "col-sm-12 col-form-label" %>
    <div class="input-group">
      <div class="input-group-text"><i class="bi bi-geo-alt-fill"></i></div>
      <%= form.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="col-sm-6 mt-1">
    <%= form.label :datetime, class: "col-sm-12 col-form-label" %>
    <div class="input-group">
      <div class="input-group-text"><i class="bi bi-calendar"></i></div>
      <%= form.datetime_select :datetime, class: "datepicker" %>
    </div>
  </div>

  <div class="col-sm-6 mt-1">
    <%= form.label :description, class: "col-sm-12 col-form-label" %>
    <div class="input-group">
      <div class="input-group-text"><i class="bi bi-clipboard"></i></div>
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="col-sm-6 mt-1">
    <%= form.label :pincode, class: "col-sm-12 col-form-label" %>
    <div class="input-group">
      <div class="input-group-text"><i class="bi bi-key-fill"></i></div>
      <%= form.text_field :pincode, class: "form-control" %>
    </div>
  </div>

  <div class="mt-4">
    <%= form.submit t("button.save"), class: "btn btn-success" %> или <%= link_to t("link.back"), :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="row d-flex justify-content-center">
  <h1>Изменение события</h1>

  <%= render "form" %>
</div>

app/views/events/index.html.erb
<div class="text-center">
  <h1 class="buffer-bottom">Все события</h1>

  <div class="row buffer-bottom">
    <%= render partial: "events/event", collection: @events %>
  </div>

  <div class="text-center">
    <% if policy(Event).create? %>
      <%= link_to t("button.new_event"), new_event_path, class: "text-center btn btn-success buffer-top" %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="row d-flex justify-content-center">
  <h1>Новое событие</h1>

  <%= render "form" %>
</div>

app/views/events/password_form.html.erb
<h1>Доступ только по пин-коду</h1>

<%= form_tag("", method: "post") do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="input-group">
    <div class="input-group-text"><i class="bi bi-key-fill"></i></div>
    <%= text_field_tag :pincode, params[:pincode], class: "form-control" %>
  </div>

  <div class="mt-4">
    <%= submit_tag t("button.send"), class: "btn btn-success", data: { turbo: false } %> или <%= link_to t("link.back"), :back %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="event">

  <div class="event-info row">

    <div class="col-md-12">
      <%= content_tag "div", "",
                      class: "event-background",
                      style: "background-image: url(#{event_photo(@event)})"
      %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description p-4">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :long %></h3>
            <h3>
              <small>
                <%= link_to @event.address, "https://yandex.ru/maps/?text=#{@event.address}" %>
              </small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-top p-4">
              <%= link_to t("button.edit_event"), edit_event_path(@event), class: "btn btn-primary mb-2" %>
              <%= link_to t("button.delete"), event_path(@event),
                          data: { turbo_method: :delete, turbo_confirm: t("turbo.confirm") }, class: "btn btn-danger mb-2 mx-2" %>
            </div>
          <% end %>
        </div>

        <div class="col-md-6">
          <div id="map" data-address="<%= @event.address %>" style="width: 100%; height: 500px" class="p-3"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photos">
        <div class="row">
          <%= render partial: "photos/photo", collection: @event.photos.except(@new_photo) %>
        </div>

        <div class="event-photo-form">
          <%= render partial: "photos/form", locals: { photo: @new_photo || @event.photos.build } %>
        </div>
      </div>

      <div class="event-comments mt-4">
        <%= render partial: "comments/form", locals: { comment: @new_comment || @event.comments.build } %>
        <div class="buffer-both col-md-8 mt-5">
          <h4>Комментарии:</h4>
          <%= render partial: "comments/comment", collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4>Зовёт:</h4>
        <p><%= render partial: "users/user", object: @event.user %></p>
      </div>

      <% if @event.subscriptions.except(@new_subscription).present? %>
        <div class="event-subscriptions">
          <h4>Пойдут:</h4>
          <div>
            <p class="">
              <%= render(
                    partial: "subscriptions/subscription",
                    collection: @event.subscriptions.except(@new_subscription)
                  ) %>
            </p>
          </div>
        </div>
      <% end %>

      <% unless @event.user == current_user %>
        <div class="event-subscription-form">
          <h4>Я пойду:</h4>
          <div class="">
            <%= render partial: "subscriptions/form", locals: { subscription: @new_subscription || @event.subscriptions.build } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>