config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  mount ResqueWeb::Engine => "/resque_web"

  root "events#index"

  resources :events do
    resources :comments, only: %i[ create destroy ]
    resources :subscriptions, only: %i[ create destroy ]
    resources :photos, only: %i[ create destroy ]

    post :show, on: :member
  end

  resources :users, only: %i[ show edit update]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  with_options if: -> { user.present? } do
    validate :self_subscription
    validates :user, uniqueness: { scope: :event_id }
  end

  with_options unless: -> { user.present? } do
    validate :email_presence
    validates :user_name, presence: true
    validates :user_email, uniqueness: { scope: :event_id }
    validates :user_email, presence: true, format: /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/
  end

  def user_name
    user&.name || super
  end

  def user_email
    user&.email || super
  end

  private

  def self_subscription
    if event.user == user
      errors.add(:user_email, :self_subscription)
    end
  end

  def email_presence
    if User.find_by(email: user_email).present?
      errors.add(:user_email, :email_presence)
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_event, only: %i[ create destroy ]
  before_action :set_subscription, only: %i[ destroy ]

  def create
    @new_subscription = @event.subscriptions.build(subscription_params)
    @new_subscription.user = current_user

    if @new_subscription.save
      EventNotificationJob.perform_later(@new_subscription)
      redirect_to @event, notice: t("controllers.subscriptions.created")
    else
      render "events/show", status: :unprocessable_entity
    end
  end

  def destroy
    message = { notice: t("controllers.subscriptions.destroyed") }

    if current_user_can_edit?(@subscription)
      @subscription.destroy!
    else
      message = { status: :unprocessable_entity }
    end

    redirect_to @event, message
  end

  private

  def set_subscription
    @subscription = @event.subscriptions.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def subscription_params
    params.fetch(:subscription, {}).permit(:user_email, :user_name)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<div class="row justify-content-center">
  <%= form_for [@event, subscription] do |form| %>
    <%= render partial: "partials/form_errors", locals: { model: subscription } %>

    <% unless user_signed_in? %>
      <div class="col-sm-6 mt-3">
        <%= form.label :user_name, class: "col-sm-6 col-form-label" %>
        <div class="input-group">
          <div class="input-group-text"><i class="bi bi-person-fill"></i></div>
          <%= form.text_field :user_name, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6 mt-1">
        <%= form.label :user_email, class: "col-sm-6 col-form-label" %>
        <div class="input-group">
          <div class="input-group-text"><i class="bi bi-mailbox"></i></div>
          <%= form.text_field :user_email, class: "form-control" %>
        </div>
      </div>
    <% end %>

    <div class="mt-4">
      <%= form.submit t("button.subscribe"), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/subscriptions/_subscription.html.erb
<span class="subscription">
  <div class="mt-2">
    <% if subscription.user.present? %>
      <%= render partial: "users/user", object: subscription.user %>
    <% else %>
      <em><%= subscription.user_name %></em>
    <% end %>
    <% if current_user_can_edit?(subscription) %>
      <%= link_to '<i class="bi bi-trash3"></i>'.html_safe, event_subscription_path(subscription.event, subscription),
                  data: { turbo_method: :delete, turbo_confirm: t("turbo.confirm") }, class: "mx-1"%>
    <% end %>
  </div>
</span>